<!-- PY-AI-ML-HEADER -->
# 📘 NumPy & Pandas
## 📝 Lec 02 Numpy And Pandas

> **Series:** Python for AI/ML &nbsp;|&nbsp; **Author:** Sriyut Singh &nbsp;|&nbsp; **Folder:** `05-numpy-and-pandas`

---
### 👇 Code & Output Below

In [1]:
import numpy as np
import pandas as pd

draft1 = pd.read_csv("S:/num py files/ex1.csv")

print(type(draft1))
draft1.head(4)

<class 'pandas.core.frame.DataFrame'>

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [2]:
import numpy as np
import pandas as pd

draft2 = pd.read_table("S:/num py files/test.tsv")

print(type(draft1))
draft2.head(4)

<class 'pandas.core.frame.DataFrame'>

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [3]:
import numpy as np
import pandas as pd

draft3 = pd.read_csv("S:/num py files/test.tsv",sep='\t')

draft3

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [4]:
import numpy as np
import pandas as pd

draft4 = pd.read_csv("S:/num py files/ex2.csv", header=None) # removing the header

draft4

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [5]:
import numpy as np
import pandas as pd

draft5 = pd.read_csv("S:/num py files/ex2.csv", names=['num1','num2','num3','num4','num5'])

draft5

   num1  num2  num3  num4   num5
0     1     2     3     4  hello
1     5     6     7     8  world
2     9    10    11    12    foo

In [6]:
import numpy as np
import pandas as pd

draft6 = pd.read_csv("S:/num py files/csv_mindex.csv")

draft6

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [7]:
import numpy as np
import pandas as pd

draft6 = pd.read_csv("S:/num py files/csv_mindex.csv",
                    index_col=['key1','key2']) # multilevel indexing
draft6

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [8]:
import numpy as np
import pandas as pd

draft7 = pd.read_csv("S:/num py files/ex4.csv",
                     skiprows=[0,2,3]) #ignoring reading foul comments

draft7

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
import numpy as np
import pandas as pd

draft8 = pd.read_csv("S:/num py files/ex5.csv") 

draft8

pd.isnull(draft8) #will show the the value which is NaN

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [10]:
import numpy as np
import pandas as pd

url="http://www.basketball-reference.com/leagues/NBA_2015_totals.html"

draft9 = pd.read_html(url) #read data from specific url
#By default the variable is itreated is list

df=draft9[0]
df.head()
df.columns #to write the names of the columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [11]:
import numpy as np
import pandas as pd

url="https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv"

draft10 = pd.read_csv(url,sep='\t') #read data from specific url
#By default the variable is itreated is list

draft10 #it is titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [12]:
import numpy as np
import pandas as pd

url="https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv"

draft10 = pd.read_csv(url,sep='\t') #read data from specific url
#By default the variable is itreated is list
draft10[['Name','Age','Survived']].head(10) # in head default value is 5

                                                Name   Age  Survived
0                            Braund, Mr. Owen Harris  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                             Heikkinen, Miss. Laina  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
4                           Allen, Mr. William Henry  35.0         0
5                                   Moran, Mr. James   NaN         0
6                            McCarthy, Mr. Timothy J  54.0         0
7                     Palsson, Master. Gosta Leonard   2.0         0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0         1
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0         1

In [13]:
import numpy as np
import pandas as pd

url="https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv"

draft11 = pd.read_csv(url,sep='\t') #read data from specific url
#By default the variable is itreated is list

# Home Work
1.WAP to count number of Survived Passengers?

2.WAp to Number of Male and Female Passengers?

3.WAP to find the maximun and minimum fare?

IN THIS WEBSITE
"https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv"

In [14]:
import numpy as np
import pandas as pd

url="https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv"

draft10 = pd.read_csv(url,sep='\t')


draft10

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [15]:
import numpy as np
import pandas as pd

url="https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv"

draft10 = pd.read_csv(url,sep='\t')


a  =  draft10['Fare']
print('This is the maximum Fare',max(a))
print('This is the minimum Fare',min(a))

This is the maximum Fare 263.0
This is the minimum Fare 6.75

In [16]:
import numpy as np
import pandas as pd

draft11 = pd.read_csv("S:/num py files/ex6.csv",nrows=10) 

draft11

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q
5  1.817480  0.742273  0.419395 -2.251035   Q
6 -0.776764  0.935518 -0.332872 -1.875641   U
7 -0.913135  1.530624 -0.572657  0.477252   K
8  0.358480 -0.497572 -0.367016  0.507702   S
9 -1.740877 -1.160417 -1.637830  2.172201   G

In [17]:
import numpy as np
import pandas as pd
chunk = pd.read_csv('S:/num py files/ex6.csv', chunksize=1000)
for i in chunk:
    print(i)

          one       two     three      four key
0    0.467976 -0.038649 -0.295344 -1.824726   L
1   -0.358893  1.404453  0.704965 -0.200638   B
2   -0.501840  0.659254 -0.421691 -0.057688   G
3    0.204886  1.074134  1.388361 -0.982404   R
4    0.354628 -0.133116  0.283763 -0.837063   Q
..        ...       ...       ...       ...  ..
995  2.311896 -0.417070 -1.409599 -0.515821   M
996 -0.479893 -0.650419  0.745152 -0.646038   H
997  0.523331  0.787112  0.486066  1.093156   D
998 -0.362559  0.598894 -1.843201  0.887292   W
999 -0.096376 -1.012999 -0.657431 -0.573315   K

[1000 rows x 5 columns]
           one       two     three      four key
1000  0.467976 -0.038649 -0.295344 -1.824726   T
1001 -0.358893  1.404453  0.704965 -0.200638   J
1002 -0.501840  0.659254 -0.421691 -0.057688   R
1003  0.204886  1.074134  1.388361 -0.982404   S
1004  0.354628 -0.133116  0.283763 -0.837063   B
...        ...       ...       ...       ...  ..
1995  2.311896 -0.417070 -1.409599 -0.515821   L
1996 -0.479893 -0.650419  0.745152 -0.646038   J
1997  0.523331  0.787112  0.486066  1.093156   V
1998 -0.362559  0.598894 -1.843201  0.887292   W
1999 -0.096376 -1.012999 -0.657431 -0.573315   D

[1000 rows x 5 columns]
           one       two     three      four key
2000  0.467976 -0.038649 -0.295344 -1.824726   1
2001 -0.358893  1.404453  0.704965 -0.200638   H
2002 -0.501840  0.659254 -0.421691 -0.057688   F
2003  0.204886  1.074134  1.388361 -0.982404   L
2004  0.354628 -0.133116  0.283763 -0.837063   E
...        ...       ...       ...       ...  ..
2995  2.311896 -0.417070 -1.409599 -0.515821   H
2996 -0.479893 -0.650419  0.745152 -0.646038   U
2997  0.523331  0.787112  0.486066  1.093156   A
2998 -0.362559  0.598894 -1.843201  0.887292   Y
2999 -0.096376 -1.012999 -0.657431 -0.573315   F

[1000 rows x 5 columns]
           one       two     three      four key
3000  0.467976 -0.038649 -0.295344 -1.824726   H
3001 -0.358893  1.404453  0.704965 -0.200638   Y
3002 -0.501840  0.659254 -0.421691 -0.057688   0
3003  0.204886  1.074134  1.388361 -0.982404   Z
3004  0.354628 -0.133116  0.283763 -0.837063   U
...        ...       ...       ...       ...  ..
3995  2.311896 -0.417070 -1.409599 -0.515821   W
3996 -0.479893 -0.650419  0.745152 -0.646038   E
3997  0.523331  0.787112  0.486066  1.093156   Q
3998 -0.362559  0.598894 -1.843201  0.887292   A
3999 -0.096376 -1.012999 -0.657431 -0.573315   M

[1000 rows x 5 columns]
           one       two     three      four key
4000  0.467976 -0.038649 -0.295344 -1.824726   H
4001 -0.358893  1.404453  0.704965 -0.200638   Z
4002 -0.501840  0.659254 -0.421691 -0.057688   2
4003  0.204886  1.074134  1.388361 -0.982404   B
4004  0.354628 -0.133116  0.283763 -0.837063   1
...        ...       ...       ...       ...  ..
4995  2.311896 -0.417070 -1.409599 -0.515821   X
4996 -0.479893 -0.650419  0.745152 -0.646038   M
4997  0.523331  0.787112  0.486066  1.093156   5
4998 -0.362559  0.598894 -1.843201  0.887292   T
4999 -0.096376 -1.012999 -0.657431 -0.573315   U

[1000 rows x 5 columns]
           one       two     three      four key
5000  0.467976 -0.038649 -0.295344 -1.824726   1
5001 -0.358893  1.404453  0.704965 -0.200638   Z
5002 -0.501840  0.659254 -0.421691 -0.057688   3
5003  0.204886  1.074134  1.388361 -0.982404   H
5004  0.354628 -0.133116  0.283763 -0.837063   B
...        ...       ...       ...       ...  ..
5995  2.311896 -0.417070 -1.409599 -0.515821   1
5996 -0.479893 -0.650419  0.745152 -0.646038   Y
5997  0.523331  0.787112  0.486066  1.093156   F
5998 -0.362559  0.598894 -1.843201  0.887292   0
5999 -0.096376 -1.012999 -0.657431 -0.573315   3

[1000 rows x 5 columns]
           one       two     three      four key
6000  0.467976 -0.038649 -0.295344 -1.824726   I
6001 -0.358893  1.404453  0.704965 -0.200638   X
6002 -0.501840  0.659254 -0.421691 -0.057688   A
6003  0.204886  1.074134  1.388361 -0.982404   C
6004  0.354628 -0.133116  0.283763 -0.837063   S
...        ...       ...       ...       ...  ..
6995  2.311896 -0.417070 -1.409599 -0.515821   P
6996 -0.479893 -0.650419  0.745152 -0.646038   9
6997  0.523331  0.787112  0.486066  1.093156   L
6998 -0.362559  0.598894 -1.843201  0.887292   5
6999 -0.096376 -1.012999 -0.657431 -0.573315   O

[1000 rows x 5 columns]
           one       two     three      four key
7000  0.467976 -0.038649 -0.295344 -1.824726   1
7001 -0.358893  1.404453  0.704965 -0.200638   I
7002 -0.501840  0.659254 -0.421691 -0.057688   H
7003  0.204886  1.074134  1.388361 -0.982404   P
7004  0.354628 -0.133116  0.283763 -0.837063   D
...        ...       ...       ...       ...  ..
7995  2.311896 -0.417070 -1.409599 -0.515821   A
7996 -0.479893 -0.650419  0.745152 -0.646038   6
7997  0.523331  0.787112  0.486066  1.093156   R
7998 -0.362559  0.598894 -1.843201  0.887292   R
7999 -0.096376 -1.012999 -0.657431 -0.573315   2

[1000 rows x 5 columns]
           one       two     three      four key
8000  0.467976 -0.038649 -0.295344 -1.824726   7
8001 -0.358893  1.404453  0.704965 -0.200638   W
8002 -0.501840  0.659254 -0.421691 -0.057688   C
8003  0.204886  1.074134  1.388361 -0.982404   S
8004  0.354628 -0.133116  0.283763 -0.837063   H
...        ...       ...       ...       ...  ..
8995  2.311896 -0.417070 -1.409599 -0.515821   W
8996 -0.479893 -0.650419  0.745152 -0.646038   N
8997  0.523331  0.787112  0.486066  1.093156   Q
8998 -0.362559  0.598894 -1.843201  0.887292   R
8999 -0.096376 -1.012999 -0.657431 -0.573315   M

[1000 rows x 5 columns]
           one       two     three      four key
9000  0.467976 -0.038649 -0.295344 -1.824726   B
9001 -0.358893  1.404453  0.704965 -0.200638   M
9002 -0.501840  0.659254 -0.421691 -0.057688   N
9003  0.204886  1.074134  1.388361 -0.982404   N
9004  0.354628 -0.133116  0.283763 -0.837063   Y
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[1000 rows x 5 columns]

In [18]:
import numpy as np
import pandas as pd
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('S:/num py files/tseries.csv')
ts

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
Freq: D, dtype: int32

In [19]:
import numpy as np
import pandas as pd
data = pd.read_csv('S:/num py files/ex5.csv')
data
data.to_csv('S:/num py files/out.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

# JSON data

In [23]:
obj="""{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}"""
#java script object notation
import json
result = json.loads(obj)


result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [24]:
print(type(result))

<class 'dict'>

In [28]:
import json
asjson = json.dumps(obj)
print(type(asjson))

<class 'str'>

In [29]:
import numpy as np
import pandas as pd
import json
sib = pd.DataFrame(result['siblings'], columns=['name','age','pets'])
sib

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

In [30]:
import numpy as np
import pandas as pd
import json
data = pd.read_json('s:/num py files/example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

# Eda

In [31]:
a='''{
    "quiz": {
        "sport": {
            "q1": {
                "question": "Which one is correct team name in NBA?",
                "options": [
                    "New York Bulls",
                    "Los Angeles Kings",
                    "Golden State Warriros",
                    "Huston Rocket"
                ],
                "answer": "Huston Rocket"
            }
        },
        "maths": {
            "q1": {
                "question": "5 + 7 = ?",
                "options": [
                    "10",
                    "11",
                    "12",
                    "13"
                ],
                "answer": "12"
            },
            "q2": {
                "question": "12 - 8 = ?",
                "options": [
                    "1",
                    "2",
                    "3",
                    "4"
                ],
                "answer": "4"
            }
        }
    }
}'''
import numpy as np
import pandas as pd
import json
c= pd.read_json(a)
c

                                                    quiz
maths  {'q1': {'question': '5 + 7 = ?', 'options': ['...
sport  {'q1': {'question': 'Which one is correct team...

In [32]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [33]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
146,147,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.0,0,0,350043,7.7958,NaN,S
147,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.0,2,2,W./C. 6608,34.3750,NaN,S
148,149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.5,0,2,230080,26.0000,F2,S
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [34]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [35]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a.describe() #only describe the numericla data

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [36]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a.dtypes[a.dtypes=='object']

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [37]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a.dtypes[a.dtypes=='object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [38]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
list_col = a.dtypes[a.dtypes=='object'].index
a[list_col].describe()

                        Name   Sex  Ticket Cabin Embarked
count                    156   156     156    31      155
unique                   156     2     145    28        3
top     Nasser, Mr. Nicholas  male  347082  C123        S
freq                       1   100       2     2      110

In [39]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    object
 4   Sex          156 non-null    object
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    object
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     object
 11  Embarked     155 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 14.8+ KB

In [40]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [41]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a.describe() #ony describe the numericla data
a[['Name','Sex','Age']]

                                                  Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0
152                                   Meo, Mr. Alfonzo    male  55.5
153                    van Billiard, Mr. Austin Blyler    male  40.5
154                              Olsen, Mr. Ole Martin    male   NaN
155                        Williams, Mr. Charles Duane    male  51.0

[156 rows x 3 columns]

In [42]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
sorted(a['Name'])[5:10:2]# check the first 15 sorted name

['Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andrew, Mr. Edgardo Samuel',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [43]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a[['Ticket']][4:9]

   Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [44]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a['Name'].describe()

count                      156
unique                     156
top       Nasser, Mr. Nicholas
freq                         1
Name: Name, dtype: object

In [45]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a['Sudh']='sriyut'
a.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sudh
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,sriyut
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,sriyut
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,sriyut
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,sriyut
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,sriyut

In [46]:
#try
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
for i in range(1):
    for i in a['Age'].any:
        if i != a['Age'] :
            print(a['PassengerId'])
#wrong

TypeError: 'method' object is not iterable

In [47]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a['Age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [48]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a[a['Age'].isnull()==True]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
46,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
76,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S
77,78,0,3,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,374746,8.0500,NaN,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
101,102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
107,108,1,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.7750,NaN,S
109,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
121,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
126,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S

In [49]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
storing_index= np.where(a['Age'].isnull()==True)
print(storing_index)

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
        48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
       126, 128, 140, 154], dtype=int64),)

In [50]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
storing_index= np.where(a['Cabin'].isnull()==False)
print(storing_index)

(array([  1,   3,   6,  10,  11,  21,  23,  27,  31,  52,  54,  55,  61,
        62,  66,  75,  88,  92,  96,  97, 102, 110, 118, 123, 124, 128,
       136, 137, 139, 148, 151], dtype=int64),)

In [51]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a[a['Cabin'].isnull()==False]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.4750,C83,S
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.0,0,0,C.A. 29395,10.5000,F33,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,F G73,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,E31,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
102,103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S
110,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,C110,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
123,124,1,2,"Webber, Miss. Susan",female,32.5,0,0,27267,13.0000,E101,S
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
136,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,D47,S
137,138,0,1,"Futrelle, Mr. Jacques Heath",male,37.0,1,0,113803,53.1000,C123,S
139,140,0,1,"Giglio, Mr. Victor",male,24.0,0,0,PC 17593,79.2000,B86,C
148,149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.5,0,2,230080,26.0000,F2,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S

In [52]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
print(a['Cabin'].isnull()==False)

0      False
1       True
2      False
3       True
4      False
       ...
151     True
152    False
153    False
154    False
155    False
Name: Cabin, Length: 156, dtype: bool

In [53]:
#have to print the non null value of cabin

import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
a['Cabin'].unique()  #will print the unique value

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [54]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
char_cabin = a['Cabin'].astype(str)#conver the data in in str

new_cabin = [cabin[0] for cabin in char_cabin] # Takes fir letter in list

new_cabin = pd.Categorical(new_cabin)
#new_cabin
new_cabin

['n', 'C', 'n', 'C', 'n', ..., 'C', 'n', 'n', 'n', 'n']
Length: 156
Categories (8, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'n']

In [55]:
import pandas as pd
import numpy as np
#import os
#import matplotilib.pyplot as plt
#%matplotlib inline
a= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
              sep='\t')
del(a['PassengerId'])
del(a['Survived'])
del(a['Pclass'])
del(a['Name'])
del(a['Sex'])
del(a['Age'])
del(a['SibSp'])
del(a['Parch'])
del(a['Ticket'])
del(a['Fare'])
del(a['Embarked'])
a[a['Cabin'].isnull()==False]

           Cabin
1            C85
3           C123
6            E46
10            G6
11          C103
21           D56
23            A6
27   C23 C25 C27
31           B78
52           D33
54           B30
55           C52
61           B28
62           C83
66           F33
75         F G73
88   C23 C25 C27
92           E31
96            A5
97       D10 D12
102          D26
110         C110
118      B58 B60
123         E101
124          D26
128        F E69
136          D47
137         C123
139          B86
148           F2
151           C2

In [56]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data= rn(5,4)
row_lables= ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_lables,column_headings)

df.iloc[2]#index position

W    0.027498
X    0.709604
Y   -1.840630
Z    0.007446
Name: C, dtype: float64

In [57]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data= rn(5,4)
row_lables= ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_lables,column_headings)

df.loc['A']#lable of row

W   -0.275456
X    1.445850
Y   -0.245395
Z   -0.624783
Name: A, dtype: float64

In [58]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data= rn(5,4)
row_lables= ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_lables,column_headings)

df['New'] = df['X']+df['Z']
    
print(df)

          W         X         Y         Z       New
A -1.373086  0.039693  0.212859 -0.901383 -0.861690
B  0.005968  1.745758 -0.319533  0.519031  2.264789
C  1.436626 -0.550667  1.483499  0.997719  0.447052
D  3.156914 -2.344290  0.420781  0.937041 -1.407249
E  0.558134 -1.142505  0.776277 -0.053479 -1.195984

In [59]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data= rn(5,4)
row_lables= ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_lables,column_headings)

df['X'].loc['C']

1.985364907028142

In [60]:
df

          W         X         Y         Z
A  0.811964  0.002503 -1.682987  1.072140
B  0.065195 -0.226803 -0.394320  1.540957
C -0.430903  1.985365 -0.903106 -0.668524
D -0.775739  0.912190  0.571291 -0.089170
E  0.411276  2.624208 -2.414557  0.609406

In [61]:
df.iloc[2,1]

1.985364907028142

In [62]:
df.iloc[1:4 , 2:4] #[rows:col]

          Y         Z
B -0.394320  1.540957
C -0.903106 -0.668524
D  0.571291 -0.089170

In [63]:
df1=df.drop('B')
df1

          W         X         Y         Z
A  0.811964  0.002503 -1.682987  1.072140
C -0.430903  1.985365 -0.903106 -0.668524
D -0.775739  0.912190  0.571291 -0.089170
E  0.411276  2.624208 -2.414557  0.609406

In [64]:
df1=df.drop('X', axis = 1)  #1 = column  , 0 = row
df1

          W         Y         Z
A  0.811964 -1.682987  1.072140
B  0.065195 -0.394320  1.540957
C -0.430903 -0.903106 -0.668524
D -0.775739  0.571291 -0.089170
E  0.411276 -2.414557  0.609406

In [65]:
print('multiple rows')
print(df.loc[['B','C']])

multiple rows
          W         X         Y         Z
B  0.065195 -0.226803 -0.394320  1.540957
C -0.430903  1.985365 -0.903106 -0.668524

In [66]:
print(df.loc[['A','E']])

          W         X         Y         Z
A  0.811964  0.002503 -1.682987  1.072140
E  0.411276  2.624208 -2.414557  0.609406

In [67]:
df.iloc[[1,2,3],[0,1]]

          W         X
B  0.065195 -0.226803
C -0.430903  1.985365
D -0.775739  0.912190

In [68]:
print('Boolean dataframe')
print(df>0)

Boolean dataframe
       W      X      Y      Z
A   True   True  False   True
B   True  False  False   True
C  False   True  False  False
D  False   True   True  False
E   True   True  False   True

In [69]:
print(df.loc[['A','B','C']]>0)

       W      X      Y      Z
A   True   True  False   True
B   True  False  False   True
C  False   True  False  False

In [1]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})# should have the same numbers of values in each
df['States'] = 'CA NV AZ'.split()
df.set_index('States',inplace=True)
print(df)

          A    B  C
States
CA      1.0  5.0  1
NV      2.0  NaN  2
AZ      NaN  NaN  3

In [3]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})# should have the same numbers of values in each
df['States'] = 'CA NV AZ'.split()
df.set_index('States',inplace=True)
print('\nDroping any rows with a NaN value\n',
     '-'*35,
     sep='')
print(df.dropna(axis=0))# 0 for row

Droping any rows with a NaN value
-----------------------------------
          A    B  C
States
CA      1.0  5.0  1

In [4]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})# should have the same numbers of values in each
df['States'] = 'CA NV AZ'.split()
df.set_index('States',inplace=True)
print('\nDroping any rows with a NaN value\n',
     '-'*35,
     sep='')
print(df.dropna(axis=1))#1 for column

Droping any rows with a NaN value
-----------------------------------
        C
States
CA      1
NV      2
AZ      3

In [9]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})# should have the same numbers of values in each
df['States'] = 'CA NV AZ'.split()
df.set_index('States',inplace=True)
print('\nDroping any rows with a minimum 2 NaN value using "threash" parameter \n',
     '-'*60)
print(df.dropna(axis=0, thresh=2))

Droping any rows with a minimum 2 NaN value using "threash" parameter
 ------------------------------------------------------------
          A    B  C
States
CA      1.0  5.0  1
NV      2.0  NaN  2

In [10]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})# should have the same numbers of values in each
df['States'] = 'CA NV AZ'.split()
df.set_index('States',inplace=True)
print('\nFilling values with a default value\n',
     '-'*35,
     sep='')
print(df.fillna(value='FILL VALUE'))

Filling values with a default value
-----------------------------------
                 A           B  C
States
CA               1           5  1
NV               2  FILL VALUE  2
AZ      FILL VALUE  FILL VALUE  3

In [12]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})# should have the same numbers of values in each
df['States'] = 'CA NV AZ'.split()
df.set_index('States',inplace=True)
print('\nFilling values with a computed value (mean of a column A here)\n',
     '-'*35,
     sep='')
print(df.fillna(value=df['A'].mean()))#will fill the mean of the values

Filling values with a computed value (mean of a column A here)
-----------------------------------
          A    B  C
States
CA      1.0  5.0  1
NV      2.0  1.5  2
AZ      1.5  1.5  3

In [14]:
import numpy as np
import pandas as pd
#Create DataFrame
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [16]:
import numpy as np
import pandas as pd
#Create DataFrame
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)
bycomp = df.groupby('Company')
bycomp#it is a variable which stores the value

In [17]:
import numpy as np
import pandas as pd
#Create DataFrame
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)
bycomp = df.groupby('Company')
print('\nGrouping the DataFrame by "company" column and listing mean sales\n',
     '-'*55,
     sep='')
print(bycomp.mean())#we can find any thing of this

Grouping the DataFrame by "company" column and listing mean sales
-------------------------------------------------------
         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [23]:
#testing
print('\nGrouping the DataFrame by "company" column and listing median sales\n',
     '-'*55,
     sep='')
print(bycomp.median())
print('\nGrouping the DataFrame by "company" column and listing sum sales\n',
     '-'*55,
     sep='')
print(bycomp.sum())

Grouping the DataFrame by "company" column and listing median sales
-------------------------------------------------------
         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

Grouping the DataFrame by "company" column and listing sum sales
-------------------------------------------------------
         Sales
Company
FB         593
GOOG       320
MSFT       464

In [24]:
df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [28]:
print("\nAll in one line of command (Stats for 'FB')\n",'-'*65, sep='')
print(pd.DataFrame(df.groupby('Company').describe().loc['FB']))#it will show in column
print('\nDifference\n',
     '-'*55)
print(pd.DataFrame(df.groupby('Company').describe().loc['FB']).transpose())# it will show in row

All in one line of command (Stats for 'FB')
-----------------------------------------------------------------
                     FB
Sales count    2.000000
      mean   296.500000
      std     75.660426
      min    243.000000
      25%    269.750000
      50%    296.500000
      75%    323.250000
      max    350.000000

Difference
 -------------------------------------------------------
   Sales
   count   mean        std    min     25%    50%     75%    max
FB   2.0  296.5  75.660426  243.0  269.75  296.5  323.25  350.0

In [3]:
import numpy as np
import pandas as pd
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [4]:
import numpy as np
import pandas as pd
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[0, 1, 2, 3])
df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [5]:
import numpy as np
import pandas as pd
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8,9,10,11])
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [6]:
df_cat1 = pd.concat([df1,df2,df3],  #will add all the dataframe or concatinate
                    axis=0)
print('\nAfter concatination along row\n','-'*30, sep='')
print(df_cat1)
df_cat1.loc[2]

After concatination along row
------------------------------
      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
0    A4   B4   C4   D4
1    A5   B5   C5   D5
2    A6   B6   C6   D6
3    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

    A   B   C   D
2  A2  B2  C2  D2
2  A6  B6  C6  D6

In [9]:
df_cat1 = pd.concat([df1,df2,df3],  #will add all the dataframe or concatinate
                    axis=0)
print('\nAfter concatination along row\n','-'*30, sep='')
print(df_cat1)
df_cat1.iloc[4]

After concatination along row
------------------------------
      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
0    A4   B4   C4   D4
1    A5   B5   C5   D5
2    A6   B6   C6   D6
3    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

A    A4
B    B4
C    C4
D    D4
Name: 0, dtype: object

In [10]:
df_cat2 = pd.concat([df1,df2,df3], 
                    axis=1)
print('\nAfter concatination along row\n','-'*30, sep='')
print(df_cat2)

After concatination along row
------------------------------
      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0   A4   B4   C4   D4  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1   A5   B5   C5   D5  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2   A6   B6   C6   D6  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [11]:
df_cat2 = pd.concat([df1,df2,df3], 
                    axis=1)
df_cat2.fillna(value='Empty', 
              inplace=True)
print('\nAfter concatination along row\n','-'*30, sep='')
print(df_cat2)

After concatination along row
------------------------------
        A      B      C      D      A      B      C      D      A      B  \
0      A0     B0     C0     D0     A4     B4     C4     D4  Empty  Empty
1      A1     B1     C1     D1     A5     B5     C5     D5  Empty  Empty
2      A2     B2     C2     D2     A6     B6     C6     D6  Empty  Empty
3      A3     B3     C3     D3     A7     B7     C7     D7  Empty  Empty
8   Empty  Empty  Empty  Empty  Empty  Empty  Empty  Empty     A8     B8
9   Empty  Empty  Empty  Empty  Empty  Empty  Empty  Empty     A9     B9
10  Empty  Empty  Empty  Empty  Empty  Empty  Empty  Empty    A10    B10
11  Empty  Empty  Empty  Empty  Empty  Empty  Empty  Empty    A11    B11

        C      D
0   Empty  Empty
1   Empty  Empty
2   Empty  Empty
3   Empty  Empty
8      C8     D8
9      C9     D9
10    C10    D10
11    C11    D11

In [12]:
#merging by a common key
left = pd.DataFrame({'key': ['K0', 'K8', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [13]:
left

  key   A   B
0  K0  A0  B0
1  K8  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [14]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [15]:
merge1 = pd.merge(left,right,
                  how='inner',#inner means first written in our case it is left
                 on='key')
merge1

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K2  A2  B2  C2  D2
2  K3  A3  B3  C3  D3

In [16]:
merge2 = pd.merge(left,right,
                  how='outer',#outer means first written in our case it is right
                 on='key')
merge2

  key    A    B    C    D
0  K0   A0   B0   C0   D0
1  K8   A1   B1  NaN  NaN
2  K2   A2   B2   C2   D2
3  K3   A3   B3   C3   D3
4  K1  NaN  NaN   C1   D1

In [18]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [21]:
merge3 = pd.merge(left,right,
                  how='left',
                 on=['key1','key2'])
merge3

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [22]:
merge3 = pd.merge(left,right,
                  how='right',
                 on=['key1','key2'])
merge3

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [24]:
merge4 = pd.merge(left,right,#will show only common as default is inner
                 on=['key1','key2'])
merge4

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

# questions

In [2]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN',  
'londON_StockhOlm', 
'Budapest_PaRis', 'Brussels_londOn'], 
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085], 
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]], 
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
'12. Air France', '"Swiss Air"']})

1. Some values in the the FlightNumber column are missing. These numbers are 
meant to increase by 10 with each row so 10055 and 10075 need to be put in 
place. Fill in these missing numbers and make the column an integer column 
(instead of a float column).

2. The From_To column would be better as two separate columns! Split each 
string on the underscore delimiter _ to give a new temporary DataFrame with 
the correct values. Assign the correct column names to this temporary 
DataFrame.

3. Notice how the capitalisation of the city names is all mixed up in this 
temporary DataFrame. Standardise the strings so that only the first letter is 
uppercase (e.g. "londON" should become "London".)

4. Delete the From_To column from df and attach the temporary DataFrame 
from the previous questions.

5. In the RecentDelays column, the values have been entered into the 
DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value 
should be NaN.

Expand the Series of lists into a DataFrame named delays, rename the columns 
delay_1, delay_2, etc. and replace the unwanted RecentDelays column in df 
with delays.

In [3]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN',  
'londON_StockhOlm', 
'Budapest_PaRis', 'Brussels_londOn'], 
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085], 
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]], 
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
'12. Air France', '"Swiss Air"']})
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"